# -*- coding: utf-8 -*-
"""Projeto matplotlib imigrações.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1W6YG-9dP3bVO0xHV3uwm8aCiYjoi2T2a

### O primeiro passo é importar a biblioteca Pandas
"""

import pandas as pd

"""### Após a importação damos carga nos arquivos criando uma variável chamada df, e usamos a função pd.read(Extensão do arquivo)(Endereço do documento)"""

df = pd.read_csv('/content/imigrantes_canada.csv')

df

"""### Com a função .info obtemos informações importantes sobre os dados: Se existem ou não dados nulos, quais são as colunas e quais os tipos de dados."""

df.info()

"""###

### A função set_index funciona para especificar uma coluna específica para ser o índice do dataframe.
"""

df.set_index('País', inplace=True)

"""### Criação de uma lista para armazenar os valores dos anos. Nesse caso anos seráo nome da lista, o comando range define os elementos dessa lista (1980 até 2013, pois para um valo antes do range final). A função Map transforma cada número dessa lista em uma str, e por fim a função list transforma esse processo numa lista real"""

anos = list(map(str,range(1980,2014)))

anos

"""### A função .loc funciona pedindo para que todas as linhas do df que tenha a palavra "Brasil" sejam coletadas e que os dados de anos que retornem sejam de acordo com a lista "anos" que acabamos de criar acima"""

brasil = df.loc['Brasil', anos]

brasil

"""### Nesse caso criamos um dicionário com as informações do Brasil sendo as chaves e as nformações de migrantes sejam os valores. Após isso transformamos esse diciionário em um df."""

brasil_dict = {'Ano': brasil.index.tolist(), 'Imigrantes': brasil.values.tolist()}
dados_brasil = pd.DataFrame(brasil_dict)

dados_brasil

"""### Importnato a biblioteca matplotlib e o módulo pyplot para gerar o primeiro gráfico."""

import matplotlib.pyplot as plt

"""### A função .plot cria um gráfico de linhas"""

plt.figure(figsize=(8,4))
plt.plot(dados_brasil['Ano'], dados_brasil['Imigrantes'])
plt.title('Imigrações do Brasil para o Canadá')
plt.xlabel('Ano')
plt.ylabel('Imigrantes')
plt.xticks(['1980','1985', '1990', '1995','2000','2005', '2010'])
plt.show()

comparacao = df.loc[['Brasil','Argentina'],anos]

comparacao

comparacao = comparacao.T

comparacao.head()

plt.plot(comparacao['Brasil'],label = 'Brasil')
plt.plot(comparacao['Argentina'],label ='Argentina')
plt.title('Imigração do Brasil e Argentina para o Canadá')
plt.xlabel('Ano')
plt.ylabel('Número de imigrantes')
plt.xticks(['1980', '1985', '1990', '1995', '2000', '2005', '2010'])
plt.legend()
plt.show()

"""### Para haver mais facilidade e diversidade na manipulação dos dados criamos uma figura com a função plt.subplots. Após, plotamos o gráfico e definimos o salto de anos no eixo X. Por fim incluímos os rótulos e a legenda do gráfico."""

fig, ax = plt.subplots(figsize=(8,4))
ax.plot(dados_brasil['Ano'], dados_brasil['Imigrantes'], lw=3, color='g')
ax.xaxis.set_major_locator(plt.MultipleLocator(5))
ax.set_title('Imigração do Brasil para o Canadá 1980 a 2013', fontsize=12, loc='left')
ax.set_xlabel('Ano', fontsize=10)
ax.set_ylabel('Número de imigrantes', fontsize=10)
ax.xaxis.set_tick_params(labelsize=10)
ax.yaxis.set_tick_params(labelsize=10)
ax.spines['top'].set_visible(False)
ax.spines['right'].set_visible(False)

fig.savefig('imigração_brasil_canada.png', transparent=False, dpi=300, bbox_inches='tight')
plt.show()

"""### Abaixo, criei dois subplots com tipos diferentes de gráficos. O axs[0] é um gráfico de linhas com as informações de imigrações. Já o axs[1] é um gráfico em boxplot com as mesmas informações de número de imigrações."""

fig, axs = plt.subplots(1,2, figsize=(15,5))
axs[0].plot(dados_brasil['Ano'], dados_brasil['Imigrantes'], lw=3)
axs[0].xaxis.set_major_locator(plt.MultipleLocator(5))
axs[0].set_title('Imigração do Brasil para o Canadá\n 1980 a 2013')
axs[0].set_xlabel('Ano')
axs[0].set_ylabel('Número de imigrantes')
axs[0].grid(linestyle='--')

axs[1].boxplot(dados_brasil['Imigrantes'])
axs[1].set_title('BoxPlot de imigrantes do Brasil para o Canadá\n1980 a 2013')
axs[1].set_xlabel('Brasil')
axs[1].set_ylabel('Número de imigrantes')
axs[1].grid(linestyle='--')

plt.show()

"""#### Nessa altura do projeto, resolvi realizar uma comparação entre a migração dos 4 maiores países da América do Sul para o Canadá dos anos de 1980 a 2013."""

fig, axs = plt.subplots(2,2, figsize=(10,6))
fig.subplots_adjust(hspace=0.5, wspace=0.3)
fig.suptitle('Comparação de imigração de países da América do Sul para o Canadá de 1980 a 2013')

axs[0,0].plot(df.loc['Brasil', anos], lw=3)
axs[0,0].xaxis.set_major_locator(plt.MultipleLocator(5))
axs[0,0].set_title('Brasil')
axs[0,0].set_xlabel('Ano')
axs[0,0].set_ylabel('Número de imigrantes')
axs[0,0].grid(linestyle='--')

axs[0,1].plot(df.loc['Argentina', anos], lw=3)
axs[0,1].xaxis.set_major_locator(plt.MultipleLocator(5))
axs[0,1].set_title('Argntina')
axs[0,1].set_xlabel('Ano')
axs[0,1].set_ylabel('Número de imigrantes')
axs[0,1].grid(linestyle='--')

axs[1,0].plot(df.loc['Colômbia', anos], lw=3)
axs[1,0].xaxis.set_major_locator(plt.MultipleLocator(5))
axs[1,0].set_title('Colômbia')
axs[1,0].set_xlabel('Ano')
axs[1,0].set_ylabel('Número de imigrantes')
axs[1,0].grid(linestyle='--')

axs[1,1].plot(df.loc['Peru', anos], lw=3)
axs[1,1].xaxis.set_major_locator(plt.MultipleLocator(5))
axs[1,1].set_title('Peru')
axs[1,1].set_xlabel('Ano')
axs[1,1].set_ylabel('Número de imigrantes')
axs[1,1].grid(linestyle='--')

for ax in axs.ravel():
  ax.set_ylim(0,7000)

plt.show()

df.head()

america_sul=df.query('Região == "América do Sul"')

america_sul

"""### Aqui estmaos criando um gráfico de barras  na horizontal para diferenciar os valores dos países da América do Sul. A instrução FOR serve para diferenciarmos os demais países do Brasil, mantendo apenas o mesmo com uma cor diferente."""

cores = []
for pais in america_sul_sorted.index:
  if pais == 'Brasil':
    cores.append('green')
  else:
    cores.append('silver')

fig, ax = plt.subplots(figsize=(12,5))
ax.barh(america_sul_sorted.index, america_sul_sorted['Total'], color=cores)
ax.set_title('América do Sul: Brasil foi o quarto país com mais imigrantes\npara o Canadá no período de 1980 a 2013', loc='Left', fontsize=18)
ax.set_xlabel("Número de imigrantes", fontsize=14)
ax.set_ylabel("")
ax.xaxis.set_tick_params(labelsize=12)
ax.yaxis.set_tick_params(labelsize=12)

for i,v in enumerate(america_sul_sorted['Total']):
  ax.text(v+20,i,str(v),color='black',fontsize=10,ha='left',va='center')

ax.set_frame_on(False)
ax.get_xaxis().set_visible(False)
ax.tick_params(axis='both', which='both', length=0)

fig.savefig('imigracao_america_sul.png',transparent=False,dpi=300,bbox_inches='tight')
plt.show()

"""### Para haver um DF com os países ordenados do maior para o menor (Em número de imigrantes nesse caso)"""

america_sul_sorted = america_sul.sort_values('Total', ascending=True)